---

- name: "Install Clam AV packages"
  ansible.builtin.apt:
    name: "{{ clamav_pkgs }}"
    state: "{{ clamav_state }}"
    update_cache: "{{ clamav_update_cache }}"
  become: true
  tags: ["ct-clamav"]

- name: "Ensure freshclam is running to keep definitions up to date"
  ansible.builtin.systemd:
    enabled: "{{ clamav_freshclam_onboot }}"
    name: "{{ clamav_freshclam_name }}"
    state: "{{ clamav_freshclam_state }}"
  become: true
  tags: ["ct-clamav"]
...
